apiVersion: v1
data:
  PORT: "5000"
  MONGO_HOST: "mongo-clusterip.default.svc.cluster.local"
  MONGO_PORT: "27017"
  MONGO_DATABASE: "devops"
  REDIS_HOST: "redis-clusterip.default.svc.cluster.local"
  REDIS_PORT: "6379"

kind: ConfigMap
metadata:
  name: express-configmap
  labels:
    app: myapp
    type: backend
