apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica1
  labels:
    app: my_app
    type: frontend

spec:
  template:
    metadata:
      name: pod2
      labels:
        app: my_app
        type: frontend
    spec:
      containers:
        - name: my-nginx
          image: nginx:alpine

  replicas: 1
  selector:
    matchLabels:
      app: my_app
      type: frontend
