apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  labels:
    type: mongodb
    app: myapp

spec:
  storageClassName: manual
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/db"
