apiVersion: v1
kind: Service
metadata:
  name: express-clusterip
  labels:
    app: myapp
    type: backend
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000

  selector:
    app: myapp
    type: backend
