apiVersion: v1
kind: Service
metadata:
  name: mongo-clusterip
  labels:
    type: mongodb
    app: myapp
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    type: mongodb
    app: myapp
