apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deployment
  labels:
    app: myapp
    type: backend

spec:
  selector:
    matchLabels:
      app: myapp
      type: backend
  replicas: 2
  template:
    metadata:
      name: express-pod
      labels:
        app: myapp
        type: backend
    spec:
      containers:
        - name: express-container
          image: lmalinowska/devops-projekt-backend
          envFrom:
            - configMapRef:
                name: express-configmap
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
