apiVersion: apps/v1
kind: Deployment

metadata:
  name: mongo-deployment
  labels:
    type: mongodb
    app: myapp

spec:
  replicas: 1
  selector:
    matchLabels:
      type: mongodb
      app: myapp
  template:
    metadata:
      name: mongo-pod
      labels:
        type: mongodb
        app: myapp
    spec:
      containers:
        - name: mongo-container
          image: mongo:latest
          envFrom:
            - configMapRef:
                name: mongo-configmap
